config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "home#index"

  # Defines the routes for the images controller
  resources :images
  post 'images/create'

  # Defines devise_for routes for users
  devise_for :users, :controllers => { :registrations => 'registrations' }

  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/create_price.rb
class CreatePrice < ApplicationRecord
require 'stripe'

Stripe.api_key = ENV['STRIPE_SECRET_KEY']

starter_subscription = Stripe::Product.create(
    name: 'Starter Subscription',
    description: '12/Month Subscription',
)

starter_subscription_price = Stripe::Price.create(
    currency: 'usd',
    unit_amount: 1200,
    recurring: {interval: 'month'},
    product: starter_subscription['id'],
)

# puts "Success! Here is the starter subscription product ID: #{starter_subscription['id']}"
# puts "Success! Here is the starter subscription price ID: #{starter_subscription_price['id']}"

end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
  mount_uploader :picture, PictureUploader
  validate :picture_size

  

  private
    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/models/payment.rb
class Payment < ActiveRecord::Base
    attr_accessor :card_number, :card_cvc, :card_expires_month, :card_expires_year
    
    belongs_to :user

    def self.month_options

        Date::MONTHNAMES.compact.each_with_index.map { |name, i| ["#{i+1} - #{name}", i+1] }

    end


    def self.year_options
            
        (Date.today.year..(Date.today.year+10)).to_a
    
    end
    

    def process_payment

        #customer = Stripe::Customer.create email: email, card: token

        #Stripe::Charge.create customer: customer.id,
        #amount: 1200,
        #description: 'Premium',
        #currency: 'usd',
        #payment_method: 'visa'

        Stripe::PaymentIntent.create({
            amount: 1000,
            currency: 'usd',
            payment_method: 'pm_card_visa',
        })

    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable

  has_one :payment
  has_many :images
  accepts_nested_attributes_for :payment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   skip_before_action :authenticate_user!, only: [:index]
  def index
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: %i[ show edit update destroy ]

  # GET /images or /images.json
  def index
    # only show images for the current user
    @images = Image.where(user_id: current_user.id)
  end

  # GET /images/1 or /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
    @image.user_id = current_user.id
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images or /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to image_url(@image), notice: "Image was successfully created." }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new, status: :unprocessable_entity, notice: "Image was not successfully created." }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1 or /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to image_url(@image), notice: "Image was successfully updated." }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1 or /images/1.json
  def destroy
    @image.destroy

    respond_to do |format|
      format.html { redirect_to images_url, notice: "Image was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def image_params
      params.require(:image).permit(:name, :picture, :user_id)
    end
    
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    def create
        build_resource(sign_up_params)
        resource.class.transaction do
            resource.save
            yield resource if block_given?
            if resource.persisted?
                @payment = Payment.new({ email: params["user"]["email"],
                                         token: params[:payment]["token"],
                                         user_id: resource.id })
                flash[:error] = "Please check registration errors" unless @payment.valid?
                begin
                    @payment.process_payment
                    @payment.save
                rescue Exception => e
                    flash[:error] = e.message
                    resource.destroy
                    puts 'Payment failed'
                    render :new and return
                end

                if resource.active_for_authentication?
                    set_flash_message! :notice, :signed_up
                    sign_up(resource_name, resource)
                    respond_with resource, location: after_sign_up_path_for(resource)
                else
                    set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
                    expire_data_after_sign_in!
                    respond_with resource, location: after_inactive_sign_up_path_for(resource)
                end
            else
                clean_up_passwords resource
                set_minimum_password_length
                respond_with resource
            end
        end
    end

    private

    #def after_sign_up_path_for(resource)
    #    'images_path'
    #end

    #def after_inactive_sign_up_path_for(resource)
    #    'images_path'
    #end

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:payment])
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/home/index.html.erb
<% if current_user %>

  <h3>Welcome: <%= current_user.email %></h3>
  
  <%= link_to 'View Photos', images_path, class: 'btn btn-primary' %>
  <%= link_to 'Upload Photo', new_image_path, class: 'btn btn-primary' %>
 

<% else %>

  <div class="jumbotron">
    <h2>Welcome to the Photo Uploading App!</h2>
    <p class="lead">
      On sign up please use the following credentials:
    </p>
    <p>• Card Number: 4242424242424242</p>
    <p>• CVC: Any 3 Digits</p>
    <p>• Month/Year: Any Future Date</p>

  </div>

  <div class="row">
    <div class="plans clearfix">
      <div class="col-lg-3 col-lg-offset-3 plan">
        <h2>Premium Plan</h2>
        <div class="price pull-right">
          Price: $10
        </div>
        <div class="features">
          <ul>
            <li>Unlimited Image Uploads</li>
            <li>Responsive design</li>
            <li>Access anywhere</li>
          </ul>
        </div>
        <p>
          <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary sign-up' %>
        </p>
      </div>
      <div class="col-lg-3 plan">
        <h2>Amaze Plan</h2>
        <div class="price pull-right">
          Price: $20
        </div>
        <div class="features">
          <ul>
            <li>Unlimited Image Uploads</li>
            <li>Responsive design</li>
            <li>Access anywhere</li>
            <li class='extra'>Unlimited projects</li>
          </ul>
        </div>
        <p>
          <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary sign-up' %>
        </p>
      </div>
    </div>
  </div>
<% end %>

app/views/images/_form.html.erb
<%= form_with model: @image, :url => images_create_path, method: :post do |f| %>

      <!-- Image Error Messages -->
      <% if @image.errors.any? %>
        <div id="error_expl" class="panel panel-danger">

          <div class="panel-heading">
            <h3 class="panel-title">
            <%= pluralize(@image.errors.count, "error") %> 
            prohibited this image from being saved:
            </h3>
          </div>

          <div class="panel-body">
            <ul>
              <% @image.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>

        </div>
      <% end %>

    <!-- Image Submition Form -->
    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :name, :class => 'form-control' %>
        </div>
    </div>

    <div class="control-group">
      <%= f.label :picture, :class => 'control-label' %>
        <div class="controls">
          <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
        </div>
    </div>

    <%= f.hidden_field :user_id, :value => @image.user_id %>
    

    <%= f.submit %>

  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
  images_path, :class => 'btn btn-default' %>

<% end %>

<script type="text/javascript">
  $('#image_picture').bind('change',function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/images/_image.html.erb
<div id="<%= dom_id image %>">
  <p>
    <strong>Name:</strong>
    <%= image.name %>
  </p>

  <p>
    <strong>Picture:</strong>
    <%= image.picture %>
  </p>

  <p>
    <strong>User:</strong>
    <%= image.user_id %>
  </p>

</div>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render "form", image: @image %>

<br>

<div>
  <%= link_to "Show this image", @image %> |
  <%= link_to "Back to images", images_path %>
</div>

app/views/images/index.html.erb
<%- model_class = Image -%>

  <div class="page-header">
    <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  </div>

  <table class="table table-striped">


      <tbody>
        <% @images.each do |image| %>
            <tr>
              <td><%= link_to image.name, image_path(image) %></td>
              <td><%= image_tag image.picture.url, size: "100x100" %></td>
              <td>
                  <%= button_to ('Destroy'),
                      image_path(image), :method => :delete,
                      :class => 'btn btn-xs btn-danger' %>
              </td>
            </tr>          
        <% end %>
      </tbody>

    

  </table>

<%= link_to ('New'), new_image_path, :class => 'btn btn-primary' %>

app/views/images/new.html.erb
<h1>New Image Upload</h1>

<%= render "form", image: @image %>

<br>

<div>
  <%= link_to "Back to images", images_path %>
</div>

app/views/images/show.html.erb
<%- model_class = Image -%>

  <div class="page-header">
    <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
  </div>

  <dl class="dl-horizontal">
    <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
    <dd><%= @image.name %></dd>
    <dt></dt>
    <dd><%= image_tag(@image.picture.url, size: "300x300") if @image.picture? %></dd>
  </dl>

<%= link_to ('Back'), images_path, :class => 'btn btn-default' %>

<%= button_to ('Destroy'), image_path(@image), :method => 'delete', :class => 'btn btn-danger' %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Photo Manager</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Home', '/', class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Images', '/images', class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Upload', '/images/new', class: "nav-link" %>
        </li>

          <% if !user_signed_in? %>
            <%= link_to "Sign in", new_user_session_path, class: 'btn btn-primary' %>
          <% else %>
             <%= link_to "Sign out", destroy_user_session_path, 'data-turbo-method': :delete, class: 'btn btn-danger logout' %>
          <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= notice if notice %>
    <%= alert if alert %>
    <%= yield %>
  </body>
</html>